changes to error handling

diff --git a/utility b/utility
--- a/utility
+++ b/utility
@@ -14,7 +14,7 @@ function categorise_directory()
             continue 
         fi
 
-        echo $directory
+        echo "$directory"
         if ! get_file_types_and_sizes $directory; then
             return $error_accessing_directory
         fi
@@ -49,10 +49,10 @@ function get_file_types_and_sizes()
         this_size=$(stat -c %s $file)
         
         if [ -v file_sizes["$this_type"] ]; then 
-            ((file_sizes["$this_type"]+=$this_size))
+            ((file_sizes["$this_type"]+=this_size))
             ((file_count["$this_type"]+=1))
         else 
-            ((file_sizes["$this_type"]=$this_size))
+            ((file_sizes["$this_type"]=this_size))
             ((file_count["$this_type"]=1))
         fi
     done
@@ -70,7 +70,7 @@ function get_file_types_and_sizes()
 
     # Try to exit the current folder and go back to previous, if unable then return
     # error accessing directory
-    cd - 1> /dev/null || return $error_accessing_directory
+    cd - > /dev/null || return $error_accessing_directory
     return 0
 }
 
@@ -91,11 +91,11 @@ function get_file_names()
     
     # Try to exit the current folder and go back to previous, if unable then return
     # error accessing directory
-    cd - 1> /dev/null || return $error_accessing_directory
+    cd - > /dev/null || return $error_accessing_directory
     return 0
 }
 
-# Handling errors produced by directory categorisation, generating UUID 1 or getting the last UUID.
+# Handling errors produced by other functions
 function handle_error()
 {
     user=$(whoami)
@@ -103,25 +103,29 @@ function handle_error()
 
     case $1 in
         $error_mac_address )
-            echo "There was a problem accessing your MAC address (error code: ${error_mac_address})" 
+            echo "There was a problem accessing your MAC address (error code: $1)" 
             echo "${current_date_and_time} | User: ${user} | Error code: $1 | Message: There was a problem accessing your MAC address." >> $log_file
             ;;
         $error_accessing_directory )
-            echo "There was a problem accessing the directory (error code: ${error_accessing_directory})"
+            echo "There was a problem accessing the directory (error code: $1)"
             echo "${current_date_and_time} | User: ${user} | Error code: $1 | Message: There was a problem accessing the directory." >> $log_file
             ;;
         $error_missing_uuid )
-            echo "There was a problem getting your last generated UUID (have you previously generated a UUID?) (error code: ${error_missing_uuid})"
+            echo "There was a problem getting your last generated UUID (have you previously generated a UUID?) (error code: $1)"
             echo "${current_date_and_time} | User: ${user} | Error code: $1 | Message: There was a problem getting your last generated UUID." >> $log_file
             ;;
         $error_wrong_num_args )
-            echo "The program has not recieved the right amount of arguments (error code: ${error_wrong_num_args})"
+            echo "The program has not recieved the right amount of arguments (error code: $1)"
             echo "${current_date_and_time} | User: ${user} | Error code: $1 | Message: The program has not recieved the right amount of arguments." >> $log_file
             ;;
+        $error_repeated_uuid )
+            echo "The UUID generated already exists. Retrying... (error code: $1)"
+            echo "${current_date_and_time} | User: ${user} | Error code: $1 | Message: The UUID generated already exists." >> $log_file
+            return 0 # Retry rather than exiting the program
+
         *)
             echo "An unknown error has occured. Please try again."
             echo "${current_date_and_time} | User: ${user} | Error code: $1 | Message: An unknown error has occured." >> $log_file
-
             ;;
     esac
     exit $1
@@ -178,7 +182,7 @@ function get_last_uuid()
     # If file exists
     if [ -f "$uuid_record_file" ]; then
         last_uuid=$(tail -n 1 $uuid_record_file)
-        echo ${last_uuid}
+        echo "${last_uuid}"
         return 0
     else
         echo "Could not generate UUID."
@@ -193,6 +197,7 @@ error_accessing_directory=1
 error_mac_address=2
 error_missing_uuid=3
 error_wrong_num_args=4
+error_repeated_uuid=5
 
 # Directories and files
 starting_directory="_Directory"
@@ -200,7 +205,7 @@ log_file="history.log"
 standard_output_file="directory_information.txt"
 uuid_record_file="uuid_history.txt"
 
-# Other varibale initialisation
+# Other variable initialisation
 this_uuid=""
 main_pid=$$
 subprocess_pid=""
@@ -232,7 +237,6 @@ do
 
             # Handle any errors
             if [[ $? -ne 0 ]]; then
-                echo error found
                 handle_error $?
             fi
 
@@ -270,13 +274,12 @@ do
 
                     # Handle any errors
                     if [[ $? -ne 0 ]]; then
-                        echo error found
                         handle_error $?
                     fi
 
                     # If the UUID has been previously generated, generate a new one
                     if [ ! -f "$uuid_record_file" ]; then
-                        while (grep "$this_uuid" $uuid_record_file)
+                        while (grep -q "$this_uuid" $uuid_record_file)
                         do 
                             # Re-generate UUID
                             echo Error: UUID generated already exists. Generating a new UUID...
@@ -288,7 +291,6 @@ do
 
                             # Handle any errors
                             if [[ $? -ne 0 ]]; then
-                                echo error found
                                 handle_error $?
                             fi
                         done
@@ -316,7 +318,7 @@ do
                     if [[ -f "$uuid_record_file" ]]; then
                         while (grep "$this_uuid" $uuid_record_file)
                         do 
-                            echo Error: UUID generated already exists. Generating a new UUID...
+                            handle_error $error_repeated_uuid
                             this_uuid=$(generate_uuid_4) &
                             subprocess_pid=$!
                             wait $subprocess_pid
@@ -324,10 +326,10 @@ do
                     fi
 
                     # Output the generated UUID
-                    echo $this_uuid
+                    echo "$this_uuid"
 
                     # Save the generated UUID to records
-                    echo $this_uuid >> $uuid_record_file
+                    echo "$this_uuid" >> $uuid_record_file
                     ;;
 
                 "last" | "l" )
@@ -344,7 +346,7 @@ do
                         handle_error $error_missing_uuid
                     fi
 
-                    echo $this_uuid
+                    echo "$this_uuid"
                     ;;
                 *)  
                     echo "${OPTARG} is not a supported UUID."
